#!/bin/bash
## A CLI for lobste.rs.
## Requirements: awk, curl, jq, sed, xargs
## Created by -- Phate6660 (phate)

json="$(curl -sSL https://lobste.rs/newest.json)"

titles="$(jq '.[].title' <<< "$json")"
titles="$(sed -e 's/^"//' -e 's/"$//' <<< "$titles")"

article_urls="$(jq '.[].url' <<< "$json")"
article_urls="$(sed -e 's/^"//' -e 's/"$//' <<< "$article_urls")"

comment_urls="$(jq '.[].comments_url' <<< "$json")"
comment_urls="$(sed -e 's/^"//' -e 's/"$//' <<< "$comment_urls")"

article_urls_space_delimited="$(xargs <<< "$article_urls")"
comment_urls_space_delimited="$(xargs <<< "$comment_urls")"

clear

read -a article_url_array <<< "$article_urls_space_delimited"
read -a comment_url_array <<< "$comment_urls_space_delimited"

awk '{print NR-1 " " $0}' <<< "$titles"

read -p "Select an article: " article

read -p "What would you like to do (view (will display links to the article and comments) / read (opens the article's link in your browser))? " action
if [ "$action" = "view" ]; then
    echo "Article: ${article_url_array[$article]}
Comments: ${comment_url_array[$article]}"
elif [ "$action" = "read" ]; then
    if [ -n "$BROWSER" ]; then
        "$BROWSER" "${article_url_array[$article]}"
    elif type -P 'xdg-open'; then
        xdg-open "${article_url_array[$article]}"
    else
        read -p "Please enter your browser's binary (e.g. firefox -- if it's in your \$PATH), or the full location of the binary (e.g. /opt/firefox/firefox): " browser
        if [[ "$browser" == *"firefox"* ]] || [[ "$browser" == *"palemoon"* ]]; then
            eval "$browser --new-tab ${article_url_array[$article]}"
        else
            eval "$browser ${article_url_array[$article]}"
        fi  
    fi
fi
