#!/bin/bash
## A CLI for lobste.rs.
## Requirements: awk, curl, jq, sed, xargs
## Created by -- Phate6660 (phate)

json="$(curl -sSL https://lobste.rs/newest.json)"
titles="$(echo "$json" | jq '.[].title')"
titles="$(sed -e 's/^"//' -e 's/"$//' <<< "$titles")"
urls="$(echo "$json" | jq '.[].comments_url')"

urls_space_delimited="$(echo "$urls" | xargs)"
read -a url_array <<< "$urls_space_delimited"

clear
echo "$titles" | awk '{print NR-1 " " $0}'

read -p "Select an article: " article

read -p "What would you like to do (view/read)? " action
if [ "$action" = "view" ]; then
    echo "${url_array[$article]}"
elif [ "$action" = "read" ]; then
    if [ -n "$BROWSER" ]; then
        "$BROWSER" "${url_array[$article]}"
    elif type -P 'xdg-open'; then
        xdg-open "${url_array[$article]}"
    else
        read -p "Please enter your browser's binary (e.g. firefox -- if it's in your \$PATH), or the full location of the binary (e.g. /opt/firefox/firefox): " browser
        if [[ "$browser" == *"firefox"* ]] || [[ "$browser" == *"palemoon"* ]]; then
            eval "$browser --new-tab ${url_array[$article]}"
        else
            eval "$browser ${url_array[$article]}"
        fi  
    fi
fi
